# 액션 이름
name: Hello Action

# 어떠한 event 실행 할것인가 
# event type https://help.github.com/en/actions/reference/events-that-trigger-workflows
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # runner 운영체제 
    runs-on: ubuntu-latest

    # 실행하는 작업들
    steps:
    #- uses: actions/checkout@v2

    # 실행될때 작업 
      # 스텝 명세서들  name -> 스텝이름 , run -> 작업할 내용
    - name: Run pwd
      run: pwd
    - name: Run ls -al
      run: ls -al
